apiVersion: v1
kind: ConfigMap
metadata:
  name: air-quality-conf
data:
  hostName: air-quality-service
  port: "3200"
---
apiVersion: v1
kind: Service
metadata:
  name: air-quality-service
  labels:
    app: air-quality
    role: api
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: air-quality
    role: api
    tier: backend
  ports:
  - port: 3200
    targetPort: 3200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-quality-service
  labels:
    app: air-quality
    role: api
    tier: backend
spec:
  selector:
    matchLabels:
      app: air-quality
      role: api
      tier: backend
  template:
    metadata:
      labels:
        app: air-quality
        role: api
        tier: backend
    spec:
      containers:
      - name: air-quality-service
        image: air-quality-service
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 3200
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3200
          failureThreshold: 30
          periodSeconds: 30
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3200
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: port
                name: air-quality-conf
          - name: HOST
            valueFrom:
              configMapKeyRef:
                  key: hostName
                  name: air-quality-conf
          - name: GEOCODE_HOST
            valueFrom:
              configMapKeyRef:
                  key: hostName
                  name: geocoding-conf
          - name: GEOCODE_PORT
            valueFrom:
              configMapKeyRef:
                  key: port
                  name: geocoding-conf