apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data: 
  username: bW9uZ28tdXNlcg==
  password: UGEkJHcwckQh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  dbHost: mongodb-service
  dbName: dev
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
    tier: backend
spec:
  selector:
    app: mongodb
    tier: backend
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-service
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
    spec:
      containers:
        - name: mongodb-service
          image: mongo:3.6.17-xenial
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          ports:
            - containerPort: 27017







