apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
      tier: backend
  template:
    metadata:
      labels:
        app: mosquitto
        tier: backend
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:1.6.2
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-config-file

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
      tier: backend
  template:
    metadata:
      labels:
        app: mosquitto
        tier: backend
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:1.6.2
          ports:
            - containerPort: 1883
